import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS PWA App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="manifest" href="/manifest.json" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next JS <a href="https://nextjs.org">PWA App</a>
        </h1>

        <p className={styles.description}>Create PWA App In Next JS</p>

        <div className={styles.grid}>
          <Link href="/about">
            <a className={styles.card}>
              <h2>About &rarr;</h2>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </a>
          </Link>

          <Link href="/contact">
            <a className={styles.card}>
              <h2>Contact &rarr;</h2>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </a>
          </Link>

          <Link href="/blog">
            <a className={styles.card}>
              <h2>Blog &rarr;</h2>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
